### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by godmar** [rehypejs/rehype-infer-title-meta#2]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

Go to [the instruction page](https://github.com/rehypejs/rehype-infer-title-meta#install)

There it says:

```
import rehypeInferReadingTimeMeta from 'https://cdn.skypack.dev/rehype-infer-title-meta@1?dts'
```

### Expected behavior

it should say:
```
import rehypeInferTitleMeta from 'https://cdn.skypack.dev/rehype-infer-title-meta@1?dts'
```

### Actual behavior

it says `rehypeInferReadingTimeMeta`

### Runtime

Deno

### Package manager

npm v7

### OS

Linux

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Nice catch, is this something you can help with perhaps?
